local String = {
  byte = string.byte,
  char = string.char,
  find = string.find,
  format = string.format,
  gmatch = string.gmatch,
  gsub = string.gsub,
  len = string.len,
  lower = string.lower,
  match = string.match,
  pack = string.pack,
  packsize = string.packsize,
  rep = string.rep,
  reverse = string.reverse,
  split = string.split,
  sub = string.sub,
  unpack = string.unpack,
  upper = string.upper
}

return String