local Table = {
  clear = table.clear,
  clone = table.clone,
  concat = table.concat,
  create = table.create,
  find = table.find,
  foreach = table.foreach,
  foreachi = table.foreachi,
  freeze = table.freeze,
  getn = table.getn,
  insert = table.insert,
  isfrozen = table.isfrozen,
  maxn = table.maxn,
  move = table.move,
  pack = table.pack,
  remove = table.remove,
  sort = table.sort,
  unpack = table.unpack,
}

return Table