return (function(Roblox, Network)
  Roblox.implementMethod("TeleportService", "GetArrivingTeleportGui", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "GetPlayerTeleportData", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "GetPlayerInstanceAsync", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "GetTeleportSetting", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "ReserveServer", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "SetTeleportGui", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "SetTeleportSetting", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "Teleport", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "TeleportAsync", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "TeleportPartyAsync", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "TeleportToPlaceInstance", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "TeleportToPrivateServer", function(_, ...)
    
  end)
  
  Roblox.implementMethod("TeleportService", "TeleportToSpawnByName", function(_, ...)
    
  end)
  
  
end)
