local Registry = {
  FpsCap = 144,
  Clipboard = "",
  GlobalVariables = {},
  ECore = {},
  ThreadEnvironments = {},
  CClosures = {},
  LightingProperty = {},
  CurrentThreadIdentity = 9,
  Game = {
    Name = "",
    GameId = 0,
    PlaceId = 0,
    UniverseId = 0,
    CreatorId = 0,
    JobId = "00000000-0000-0000-0000-000000000000",
    PlaceVersion = 0,
    PrivateServerId = 0,
    PrivateServerOwnerId = 0
  },
  CachedInstances = {},
  NilInstances = {},
  RawMetatables = {},
  CallbackStorage = {},
  currentNamecall = "",
  FFlags = {},
  SecuredInstances = {},
  ReadonlyTables = {},
  DrawingCache = {},
  HWID = "f3b9c1a2-7d8e-4f5b-9a2c-1d3e4f6b7c8d"
}

return Registry